AWSTemplateFormatVersion: "2010-09-09"
Description: This CloudFormation template provisions an unencrypted S3 Bucket
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Delete
    Properties:
      BucketName: examplebuketcreatedfromcloudformation